import React, { useEffect, useState } from 'react';
import { apiClient } from '../../api/client';
import { Student, Interview } from '../../types';
import { TimelineView } from '../../components/schedule/TimelineView';

import { useOperations } from '../../store/operationsStore';

export const StudentSchedulePage: React.FC = () => {
  const { scheduleVersion, syncCounter } = useOperations();
  const [profile, setProfile] = useState<Student | null>(null);
  const [interviews, setInterviews] = useState<Interview[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    apiClient.get('/students/me/profile').then((res) => {
      setProfile(res.data);
      return apiClient.get(`/schedule/interviews?student_id=${res.data.id}`);
    }).then((res) => {
      if (res) setInterviews(res.data);
    }).catch(console.error)
      .finally(() => setIsLoading(false));
  }, [scheduleVersion, syncCounter]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12 text-sand-600 text-sm font-medium">
        Loading interview timetable...
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="bg-white p-5 rounded-lg border border-sand-300 shadow-xs flex flex-wrap justify-between items-center gap-4">
        <div>
          <h2 className="text-xl font-bold text-sand-900 tracking-tight">MY INTERVIEW TIMETABLE</h2>
          <p className="text-xs text-sand-600 mt-1">
            Detailed schedule for candidate {profile?.name || 'Alex Mercer'} ({profile?.student_code || 'S0421'}) • Department of {profile?.branch || 'ISE'}
          </p>
        </div>
        <div className="text-right">
          <span className="text-xs font-semibold text-sand-700 bg-sand-100 px-3 py-1.5 rounded-md border border-sand-300">
            {interviews.length} Confirmed {interviews.length === 1 ? 'Interview' : 'Interviews'}
          </span>
        </div>
      </div>

      {interviews.length === 0 ? (
        <div className="bg-white p-8 rounded-lg border border-sand-300 text-center space-y-2">
          <p className="text-sand-800 font-semibold text-sm">No interviews scheduled yet</p>
          <p className="text-sand-500 text-xs max-w-md mx-auto">
            The placement schedule has not been generated by the Placement Coordinator yet. Once generated, your company interview time slots and room allocations will automatically appear here.
          </p>
        </div>
      ) : (
        <TimelineView interviews={interviews} filterStudentId={profile?.id} />
      )}
    </div>
  );
};
