import React, { useEffect, useState } from 'react';
import { apiClient } from '../../api/client';
import { Company, Interview } from '../../types';
import { TimelineView } from '../../components/schedule/TimelineView';

import { useOperations } from '../../store/operationsStore';

export const CompanySchedulePage: React.FC = () => {
  const { scheduleVersion, syncCounter } = useOperations();
  const [company, setCompany] = useState<Company | null>(null);
  const [interviews, setInterviews] = useState<Interview[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    apiClient.get('/companies/me/profile').then((res) => {
      setCompany(res.data);
      return apiClient.get(`/schedule/interviews?company_id=${res.data.id}`);
    }).then((res) => {
      if (res) setInterviews(res.data);
    }).catch(console.error)
      .finally(() => setIsLoading(false));
  }, [scheduleVersion, syncCounter]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12 text-sand-600 text-sm font-medium">
        Loading company interview schedule...
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="bg-white p-5 rounded-lg border border-sand-300 shadow-xs flex flex-wrap justify-between items-center gap-4">
        <div>
          <h2 className="text-xl font-bold text-sand-900 tracking-tight">COMPANY INTERVIEW SCHEDULE</h2>
          <p className="text-xs text-sand-600 mt-1">
            Complete interview schedule for {company?.name || 'TechNova Systems'} with dedicated room and panel allocation
          </p>
        </div>
        <div className="text-right">
          <span className="text-xs font-semibold text-sand-700 bg-sand-100 px-3 py-1.5 rounded-md border border-sand-300">
            {interviews.length} Scheduled {interviews.length === 1 ? 'Slot' : 'Slots'}
          </span>
        </div>
      </div>

      {interviews.length === 0 ? (
        <div className="bg-white p-8 rounded-lg border border-sand-300 text-center space-y-2">
          <p className="text-sand-800 font-semibold text-sm">No interviews scheduled yet</p>
          <p className="text-sand-500 text-xs max-w-md mx-auto">
            The placement schedule has not been generated by the Placement Coordinator yet. Once generated, your company's interview slots and panel room assignments will automatically appear here.
          </p>
        </div>
      ) : (
        <TimelineView interviews={interviews} filterCompanyId={company?.id} />
      )}
    </div>
  );
};
